### ISSUE TITLE
Recover password is not working

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#163]
SwellRT returns a 200 OK to the recover_password POST. After that, the old password is the one that still works

**Comment by pablojan** [comment]
Can't reproduce. Tested in v0.50.3-alpha:
- Password changed with token
- Password changed with old password

Can you provide more info? environment, user's data...

**Comment by atd** [comment]
Environment: production
User: atd

Did you try your own user in production?

**Comment by pablojan** [comment]
The issue is reproduced in production. It seems that password service expects a full wave user name (e.g. atd@prototype.p2pvalue.eu), but it doesn't fail.

The link sent by email, includes a simple user id ("pablojan")

`https://app.teem.works:443/session/recover_password?token=<token>&id=pablojan`

trying this changed url, the password change works:

`https://app.teem.works:443/session/recover_password?token=<token>&id=pablojan@prototype.p2pvalue.eu`
