### ISSUE TITLE
Google Chrome: KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54

### ISSUE THREAD

**Issue by jkamuf2s** [P2Pvalue/swellrt#213]
If you use  a version of google chrome greater then Version 53 and you have a `Collaborative Text Editor` instance then if the user types something into the `<div id="editor-panel"/></div>`  then you will get this error in the browser console and your keyboard input does not get processed:

![screenshot 1468](https://cloud.githubusercontent.com/assets/7395542/23758161/1b9cc830-04e9-11e7-879f-a76c86682fac.jpg)

I am pretty sure this is the reason because of the new google chrome version, because when I use an older version it works but if I type I get this warning in the console:
`Google Chrome: KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54`
![screenshot 1467](https://cloud.githubusercontent.com/assets/7395542/23758178/30acf38a-04e9-11e7-9ff9-624a604bc4d3.jpg)

**Comment by pablojan** [comment]
This issue was fixed some months ago in our master branch, but probably not
in old alpha releases. To move to our new beta branch you should git clone
the repo and built swellrt manually. Please take into account that all
Swellrt API has been evolved to a new beta version, no back compatible.

If you have any doubt or comment please contact me.

Thanks
