### ISSUE TITLE
swellrt version and jetpad version

### ISSUE THREAD

**Issue by zmhbh** [P2Pvalue/swellrt#234]
@pablojan Hi, I am using latest master branchs of swellrt and jetpad, but they just can't connect with each other and show this error:
<img width="664" alt="screen shot 2018-03-09 at 11 33 16 am" src="https://user-images.githubusercontent.com/9757323/37226357-80021e3c-238e-11e8-93cf-4905c2224899.png">

Can you please point out what are the corresponding versions/branches I should use? Thank you so much!

**Comment by pablojan** [comment]
Hi Jingyu,

The latest version of jetpad (latest version in master) works only with
last alpha versión of swellrt (
https://github.com/P2Pvalue/swellrt/releases/tag/v0.57.24-alpha)
We are improving swellrt this first quarter of the year in order to upgrade
jetpad during Q2.


2018-03-09 20:41 GMT+01:00 Jingyu Huang <notifications@github.com>:

**Comment by zmhbh** [comment]
Thanks!
